# Generated by Django 2.1.7 on 2019-02-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190225_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_visits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Відвідування',
                'verbose_name_plural': 'Відвідування',
            },
        ),
    ]
