# Generated by Django 2.1.7 on 2019-02-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='student_visits',
        ),
        migrations.AddField(
            model_name='visits',
            name='student',
            field=models.OneToOneField(max_length=246, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Відвідування'),
        ),
    ]
