# Generated by Django 2.1.7 on 2019-02-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190228_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='student_visits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Visits', verbose_name='Відвідування'),
        ),
        migrations.AddField(
            model_name='visits',
            name='visit',
            field=models.OneToOneField(max_length=246, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Студент'),
        ),
    ]
