# Generated by Django 2.1.7 on 2019-02-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20190228_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_visits',
            new_name='visits_of_students',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='visit',
            new_name='student_name',
        ),
    ]
