# Generated by Django 2.1.7 on 2019-02-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20190228_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='visits_of_students',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='student_name',
        ),
        migrations.AddField(
            model_name='visits',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
