# Generated by Django 2.1.7 on 2019-02-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20190228_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='student',
        ),
        migrations.AddField(
            model_name='visits',
            name='stud',
            field=models.OneToOneField(blank=True, max_length=246, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='Студент'),
        ),
    ]
