# Generated by Django 2.1.7 on 2019-02-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20190228_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='stud',
        ),
    ]
